export const images = {
    logo: require("./png/logo.png"),
    circles: require("./png/circles.png"),
    circles2: require("./png/circles2.png"),
    circles3: require("./png/cirlces3.png"),
    tick: require("./png/tick.png"),
    burgerMenu: require("./png/burgerMenu.png"),
    search: require("./png/search.png"),
    profile: require("./png/profile.png"),
    profile2: require("./png/profile2.png"),
    profile3: require("./png/profile3.png"),
    profile4: require("./png/profile4.png"),
    backArrow: require("./png/backArrow.png"),
    add: require("./png/add.png"),
    post1: require("./png/post1.png"),
    share: require("./png/share.png"),
    rePost: require("./png/rePost.png"),
    heart: require("./png/heart.png"),
    graph: require("./png/graph.png"),
    graph2: require("./png/graph2.png"),
    home: require("./png/home.png"),
    home2: require("./png/home2.png"),
    user: require("./png/user.png"),
    user2: require("./png/user2.png"),
}